"""change colums in city_name and transport tables

Revision ID: 05197a746cc3
Revises: 52e47e691c85
Create Date: 2023-07-18 10:44:21.045548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05197a746cc3'
down_revision = '52e47e691c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_name', sa.Column('send', sa.Boolean(), nullable=True))
    op.add_column('transport', sa.Column('send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'send')
    op.drop_column('city_name', 'send')
    # ### end Alembic commands ###
