"""int

Revision ID: 52e47e691c85
Revises: 
Create Date: 2023-07-18 10:24:09.595957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e47e691c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clid', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_name.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('route', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_name'], ['city_name.id'], ),
    sa.ForeignKeyConstraint(['route'], ['route.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport')
    op.drop_table('route')
    op.drop_table('vehicle_type')
    op.drop_table('city_name')
    # ### end Alembic commands ###
