"""change colums in city_name and transport tables v2

Revision ID: a53680d88e49
Revises: 05197a746cc3
Create Date: 2023-07-18 10:45:10.515967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53680d88e49'
down_revision = '05197a746cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
